language: bash

sudo: required

services:
  - docker

before_install:
  - docker pull koalaman/shellcheck

script:
 - "docker run -v $(pwd):/scripts koalaman/shellcheck /scripts/bind-wallpaper.sh"

matrix:
  fast_finish: true
